relevant_words = [
    'google', 'acquisition', 'ai', 'algorithm', 'alphabet', 'amazon', 'analytics', 'announcement',
    'apple', 'artificial intelligence', 'blockchain', 'business', 'ceo', 'cloud',
    'competition', 'cybersecurity', 'data', 'data analysis', 'data privacy',
    'development', 'digital', 'digital business', 'digital era', 'digital future',
    'digital innovation', 'digital marketing', 'digital platform', 'digital revolution',
    'digital services', 'digital strategy', 'digital transformation', 'disruption',
    'disruptive innovation', 'disruptive technology', 'earnings', 'ecommerce',
    'economic', 'emerging technology', 'entrepreneurship', 'expansion', 'facebook',
    'financial results', 'finance', 'future', 'global', 'global market', 'growth',
    'growth strategy', 'hardware', 'impact', 'industry', 'innovative', 'innovation',
    'innovation ecosystem', 'innovator', 'internet', 'internet business',
    'internet of things', 'internet platform', 'investors', 'investment', 'investment opportunity',
    'ipo', 'machine learning', 'market', 'market disruption', 'marketplace', 'microsoft',
    'mobile', 'mobile apps', 'mobile devices', 'mobile technology', 'nasdaq', 'netflix',
    'online', 'online advertising', 'partnership', 'performance', 'platform',
    'product', 'profits', 'revenue', 'research', 'services', 'shareholders', 'smartphones',
    'social media', 'software', 'software development', 'startup', 'startup ecosystem',
    'stock', 'strategy', 'success', 'tech advancements', 'tech company', 'tech culture',
    'tech development', 'tech industry', 'tech innovation', 'tech market', 'tech stocks',
    'tech trends', 'technology', 'technology company', 'technology innovation', 'technology investment',
    'technology sector', 'tesla', 'trends', 'venture capital', 'virtual reality', 'employees', 'shocked', 'Samsung',
    'replacing', 'interesting', 'panic', 'contract', 'competitors', 'upgrading', 'engineers', 'executives', 'designers',
    'sprint', 'personalized', 'brainstorm', 'medical', 'diagnosis', 'people', 'chatbot', 'phones', 'robot', 'interview',
    'podcast', 'revolution', 'state-of-the-art', 'secretive', 'smarter', 'invalidated', 'japanese', 'viral',
    'video', 'boston dynamics', 'hyundai', 'humanoid', 'court', 'epic games', 'federal', 'courthouse', 'legal', 'battle',
    'apps', 'judge', 'jury', 'exploiting', 'forced', 'settlement', 'damages', 'fee', 'billion', 'sony', 'playstation',
    'bot', 'active', 'inactive', 'update', 'witness', 'ukraine', 'russia', 'israel', 'palestine',
    'hamas', 'monopoly', 'war', 'abuse', 'abusing', 'maps', 'die', 'died', 'kill', 'killed'
]
